### Prueba 1: Jaume (Nuevo deporte y viaje)
POST http://localhost:3000/chat
Content-Type: application/json

{
  "userId": "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11",
  "message": "Hello. My name is Jaume, I'm 19 years old, and I love go running. I recently went on a trip to portaventura with my friends and it was amazing!"
}

### Prueba 2: Jaume (Cambio de deporte)
POST http://localhost:3000/chat
Content-Type: application/json

{
  "userId": "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11",
  "message": "I just get tired of running, so I decided to start swimming instead."
}