import { ApiProperty } from '@nestjs/swagger';

export class ChatResponseDto {
  @ApiProperty({
    example: 'La gravedad es la fuerza de atracción entre dos masas...',
    description: 'The response generated by the AI',
  })
  answer!: string;
}
